name: deploy


# Controls when the action will run. 
on:

  push:
    branches: [ main ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: app/
        remote_path: /var/www/studio8-kosmetik.de/
        # remote_host: 116.203.246.171
        remote_host: studio8-kosmetik.de
        remote_user: studio8
        remote_key: ${{ secrets.GIT_STUDIO8_KOSMETIK }}