name: Docker

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: app/
        remote_path: /var/www/studio8-kosmetik.de/
        remote_host: 116.203.246.171
        # remote_host: studio8-kosmetik.de
        remote_user: studio8
        remote_key: ${{ secrets.GIT_STUDIO8_KOSMETIK }}